-- Q29 | TCD5 — UMA query. Totais = geração DESTE projeto.nome

SELECT
  CAST('TCD5_total' AS NVARCHAR(40)) AS "Check",
  CAST(COUNT(*) AS NVARCHAR(50)) AS "Valor"
FROM TCD5 T5
INNER JOIN OTCD T0 ON T5."TcdId" = T0."AbsId"
WHERE T0."TcdType" = 'MI'

UNION ALL
SELECT 'UsageCode_vazio', CAST(COUNT(*) AS NVARCHAR(50))
FROM TCD5 T5
INNER JOIN OTCD T0 ON T5."TcdId" = T0."AbsId"
WHERE T0."TcdType" = 'MI' AND T5."UsageCode" IS NULL

UNION ALL
SELECT 'Usage_nao_OUSG', CAST(COUNT(*) AS NVARCHAR(50))
FROM TCD5 T5
INNER JOIN OTCD T0 ON T5."TcdId" = T0."AbsId"
WHERE T0."TcdType" = 'MI'
  AND NOT EXISTS (SELECT 1 FROM OUSG U WHERE U."ID" = T5."UsageCode")

UNION ALL
SELECT 'TaxCode_nao_OSTC', CAST(COUNT(*) AS NVARCHAR(50))
FROM TCD5 T5
INNER JOIN OTCD T0 ON T5."TcdId" = T0."AbsId"
WHERE T0."TcdType" = 'MI'
  AND T5."TaxCode" IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM OSTC S WHERE S."Code" = T5."TaxCode")

UNION ALL
SELECT 'TCD5_sem_TCD3', CAST(COUNT(*) AS NVARCHAR(50))
FROM TCD5 T5
INNER JOIN OTCD T0 ON T5."TcdId" = T0."AbsId"
WHERE T0."TcdType" = 'MI'
  AND NOT EXISTS (SELECT 1 FROM TCD3 T3 WHERE T3."AbsId" = T5."Tcd3Id")

ORDER BY 1
-- UsageCode_vazio, Usage_nao_OUSG, TaxCode_nao_OSTC, TCD5_sem_TCD3 = 0
